# 🎬 Movie Recommendation Model

## Objective

Build a content-based movie recommendation system using:

- NLP preprocessing
- Stemming
- CountVectorizer
- Cosine Similarity

In [2]:
import pandas as pd
import numpy as np
import nltk

In [3]:
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
new_df = pd.read_csv("../data/movie_features.csv")

new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [5]:
new_df.shape

(4800, 3)

In [6]:
ps = PorterStemmer()

In [7]:
def stem(text):

    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [8]:
new_df["tags"] = new_df["tags"].apply(stem)

In [9]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [11]:
cv = CountVectorizer(
    max_features=5000,
    stop_words="english"
)

In [13]:
vectors = cv.fit_transform(new_df["tags"]).toarray()

In [14]:
vectors.shape

(4800, 5000)

In [15]:
similarity = cosine_similarity(vectors)

In [16]:
similarity.shape

(4800, 4800)

In [17]:
def recommend(movie):
    movie_index = new_df[new_df["title"] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [18]:
recommend("Avatar")

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [19]:
import pickle

In [30]:
pickle.dump(
    new_df,
    open("../models/movies.pkl", "wb")
)

print("movies.pkl saved successfully!")

movies.pkl saved successfully!

In [31]:
pickle.dump(
    similarity,
    open("../models/similarity.pkl", "wb")
)

print("similarity.pkl saved successfully!")

similarity.pkl saved successfully!

In [32]:
import os

print(os.listdir("../models"))

['movies.pkl', 'similarity.pkl']